version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      - ZOOKEEPER_CLIENT_PORT=${ZOOKEEPER_PORT:-2181}
      - ZOOKEEPER_TICK_TIME=${ZOOKEEPER_TICK_TIME:-2000}
    volumes:
      - ./volumes/zookeeper/data:/var/lib/zookeeper/data
      - ./volumes/zookeeper/log:/var/lib/zookeeper/log
    networks:
      - car-rental-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "${KAFKA_PORT:-9092}:9092"
    environment:
      - KAFKA_BROKER_ID=${KAFKA_BROKER_ID:-1}
      - KAFKA_ZOOKEEPER_CONNECT=${ZOOKEEPER_SERVICE_NAME:-zookeeper}:${ZOOKEEPER_PORT:-2181}
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${KAFKA_SERVICE_NAME:-kafka}:${KAFKA_INTERNAL_PORT:-29092},PLAINTEXT_HOST://localhost:${KAFKA_PORT:-9092}
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=${KAFKA_REPLICATION_FACTOR:-1}
    volumes:
      - ./volumes/kafka/data:/var/lib/kafka/data
    networks:
      - car-rental-network

  redis:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD:-redispass}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - ./volumes/redis/data:/data
    networks:
      - car-rental-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:${REDIS_SERVICE_NAME:-redis}:${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redispass}
    ports:
      - "${REDIS_COMMANDER_PORT:-8081}:8081"
    depends_on:
      - redis
    networks:
      - car-rental-network

  kafka-websocket-connector:
    build:
      context: ./services/kafka-websocket-connector
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - redis
      - zookeeper
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_SERVICE_NAME:-kafka}:${KAFKA_INTERNAL_PORT:-29092}
      - REDIS_HOST=${REDIS_SERVICE_NAME:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redispass}
      - ZOOKEEPER_HOST=${ZOOKEEPER_SERVICE_NAME:-zookeeper}
      - ZOOKEEPER_PORT=${ZOOKEEPER_PORT:-2181}
    networks:
      - car-rental-network

volumes:
  zookeeper-data:
  zookeeper-logs:
  kafka-data:
  redis-data:
  car-rental-data:

networks:
  car-rental-network:
    driver: bridge
